### ISSUE TITLE
`HTML` canvas issues

### ISSUE THREAD

**Issue by TodePond** [TodePond/Habitat#17]
There are some issues when making a canvas with the `HTML` function.

**Comment by Magnogen** [comment]
What are the issues?

**Comment by l2wilson94** [comment]
If you do this, it doesn't work:
```js
const canvas = HTML `<canvas></canvas>`
document.body.appendChild(canvas)
```

You have to do this instead:
```js
document.create("canvas")
document.body.appendChild(canvas)
```

**Comment by TodePond** [comment]
This is now fixed in the new version: https://github.com/TodePond/Habitat/commit/1950dc385a378d57b0cfbcdf3a5eb71f9706562d
