### ISSUE TITLE
Principles Document?

### ISSUE THREAD

**Issue by TodePond** [TodePond/Habitat#22]
There should be a rough guide for the principles/goals/style of the Habitat library, so that it is easier for people (including me) to contribute to the library!

**Comment by Magnogen** [comment]
Pogchamp

**Comment by TodePond** [comment]
Started roughly here: https://todepond.gitbook.io/way-of-tode/

**Comment by TodePond** [comment]
I've been thinking about this and I think it would be good as more of an 'encyclopedia' that you dip into out-of-order, rather than something that is intended to be read from start to finish.

**Comment by TodePond** [comment]
Related to #36 
Those helper functions will determine this
