### ISSUE TITLE
`memo`

### ISSUE THREAD

**Issue by TodePond** [TodePond/Habitat#53]
Auto function memo-iser

**Comment by enbyautumn** [comment]
Hi i couldnt see any repo-specific contribution guidelines, would it be okay if i worked on a PR adding this?

**Comment by TodePond** [comment]
If you'd like to! :) I can always clean up things to make it fit in with the rest of the library afterwards!

Btw, I'm planning to do a re-organise of this repo soon anyway, so I can port over anything you do to the new version (if you do want to go ahead)

**Comment by enbyautumn** [comment]
Opened #57

**Comment by TodePond** [comment]
Done: #57
